<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Visi extends MY_backend
{
    function __construct()
    {
        parent::__construct();

		
		$GLOBALS['folder_about_us_img'] = 'public/profil/';
		$GLOBALS['folder_file'] = 'public/profil/';
		$this->allowed_types = array('jpg','jpeg','png','gif');
		$this->file_size = array(0,7000);		
        //library breadcrum/untuk navigasi
		$this->load->library('breadcrumb');
		$this->load->library('urlcrypt');
		
		//breadcrumb untuk navigasi
		$this->breadcrumb->add_crumb('Home');
		$this->breadcrumb->add_crumb('Tentang kami');
		
		$this->data['primary_title'] = '<i class="fa fa fa-gear"></i> Tentang kami';
		$this->data['sub_primary_title'] = '';
		
		$this->data['sub_title'] = 'Tentang kami';
		$this->layout->set_title($this->data['sub_title']);
			
		$this->validation_rule();
    }
	
	// {VALIDATION RULE} //
	public function validation_rule(){
		$this->data['rules'] = array(
		);
		$this->data['rules_message'] = array();
	}
	
	function index(){
		$this->rule->type('U');
		
		$this->wd_validation->run_validate_js($this->data['rules'],$this->data['rules_message'],'#dt_form','.validate-js-message');
		
		
		$this->layout->set_include_group('form');
		$this->layout->set_include('inline',getview('form_js')); 

		$this->data['list']['visi'] = get_wd_options('visi');
		
		$this->layout->theme('backend','edit', $this->data);	
	}
	
	function update_action(){
		$this->rule->type('U');		
		$id = $this->input->post('id');
		$id = $this->urlcrypt->decode($id);

		if($this->ci_validation()==FALSE)
			redirect(admin_dir().this_module());

		$data = array(
			'visi' => $this->input->post('visi'),
		);
		foreach ($data as $name => $value) 
			$this->wd_db->edit_dml('wd_options', array('value' => $value) , array( 'name' => $name));

			
		redirect(admin_dir().this_module());	
	}
	
}




/* End of file Tentang_kami.php */
/* Location: ./application/modules/tentang_kami/controllers/Tentang_kami.php */
/* Please DO NOT modify this information : */
/* Generated by IndonesiaIT Codeigniter CRUD Generator 2017-08-11 18:45:56 */
/* indonesiait.com */