<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_index extends CI_Model
{
    public function __construct()
	{
		parent::__construct();
		$this->load->database();
	}
}





/* End of file M_index.php */
/* Location: ./application/modules/service/models/M_index.php */
/* Please DO NOT modify this information : */
/* Generated by IndonesiaIT Codeigniter CRUD Generator 2019-03-11 11:44:37 */
/* indonesiait.com */