<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Tentang_kami extends MY_backend
{
    function __construct()
    {
        parent::__construct();

		
		$GLOBALS['folder_about_us_img'] = 'public/profil/';
		$GLOBALS['folder_file'] = 'public/profil/';
		$this->allowed_types = array('jpg','jpeg','png','gif');
		$this->file_size = array(0,7000);		
        //library breadcrum/untuk navigasi
		$this->load->library('breadcrumb');
		$this->load->library('urlcrypt');
		
		//breadcrumb untuk navigasi
		$this->breadcrumb->add_crumb('Home');
		$this->breadcrumb->add_crumb('Tentang kami');
		
		$this->data['primary_title'] = '<i class="fa fa fa-gear"></i> Tentang kami';
		$this->data['sub_primary_title'] = '';
		
		$this->data['sub_title'] = 'Tentang kami';
		$this->layout->set_title($this->data['sub_title']);
			
		$this->validation_rule();
    }
	
	// {VALIDATION RULE} //
	public function validation_rule(){
		$this->data['rules'] = array(
		);
		$this->data['rules_message'] = array();
	}
	
	function index(){
		$this->rule->type('U');
		
		$this->wd_validation->run_validate_js($this->data['rules'],$this->data['rules_message'],'#dt_form','.validate-js-message');
		
		
		$this->layout->set_include_group('form');
		$this->layout->set_include('inline',getview('form_js')); 

		$this->data['list']['about_us'] = get_wd_options('about_us');
		$this->data['list']['about_us_img'] = get_wd_options('about_us_img');
		
		$this->layout->theme('backend','edit', $this->data);	
	}
	
	function update_action(){
		$this->rule->type('U');		
		$id = $this->input->post('id');
		$id = $this->urlcrypt->decode($id);

		if($this->ci_validation()==FALSE)
			redirect(admin_dir().this_module());
		
		$about_us_img = get_wd_options('about_us_img');
		if (isset($_FILES['about_us_img']['name']) && $_FILES['about_us_img']['name']!= '') {
			check_files('about_us_img','',$this->file_size,$this->allowed_types);
			$updata = file_upload($GLOBALS['folder_about_us_img'],'about_us_img');
			if ($updata['error']==1) {
				$this->session->set_flashdata('danger_message', 'Error uploading file !!');
				redirect(admin_dir().this_module());
				exit();
			}
			@unlink($GLOBALS['folder_about_us_img'].$about_us_img);
			$about_us_img = $updata['name'];
		}
			

		
		$buku_panduan = get_wd_options('buku_panduan');

		if (isset($_FILES['file']['name']) && $_FILES['file']['name']!= '') {
			check_files('file','',array(0,5000),array('pdf','docx','doc'));
			$updata = file_upload($GLOBALS['folder_file'],'file');
			if ($updata['error']!='') {
				$this->session->set_flashdata('danger_message', 'Error uploading file !!');
				redirect(admin_dir().this_module());
				exit();
			}
			@unlink($GLOBALS['folder_file'].$buku_panduan);						
			$buku_panduan = $updata['name'];
		}

		$data = array(
			'about_us' => $this->input->post('about_us'),
			'about_us_img' => $about_us_img,
		);
		foreach ($data as $name => $value) 
			$this->wd_db->edit_dml('wd_options', array('value' => $value) , array( 'name' => $name));

			
		redirect(admin_dir().this_module());	
	}
	
}




/* End of file Tentang_kami.php */
/* Location: ./application/modules/tentang_kami/controllers/Tentang_kami.php */
/* Please DO NOT modify this information : */
/* Generated by IndonesiaIT Codeigniter CRUD Generator 2017-08-11 18:45:56 */
/* indonesiait.com */